version: "3.8"

services:
  frontend:
    image: "julianlechner/dj-frontend:latest"
    container_name: "frontend"
    ports:
      - "80:3000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  fastapi:
    image: "julianlechner/dj-backend:latest"
    container_name: fastapi
    ports:
      - "8000:8000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - tunetoss-data:/app/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 30 --label-enable --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  tunetoss-data: